name: web_server
description: "A cross-platform Flutter/Dart LAN file sharing server. Easily upload, download, delete, and browse files or folders via a beautiful web interface. Works on desktop, mobile, and embedded devices, making local file access and management simple and efficient."
version: 1.0.0
homepage: https://github.com/lianleven/web_server
repository: https://github.com/lianleven/web_server
documentation: https://github.com/lianleven/web_server/blob/main/README.md


environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  archive: ^3.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - lib/assets/index.html
