name: lan_web_server
description: "A cross-platform LAN file sharing server with a simple web interface for uploading, downloading, and managing files."
version: 1.0.1+2
homepage: https://github.com/lianleven/lan_web_server
repository: https://github.com/lianleven/lan_web_server
documentation: https://github.com/lianleven/lan_web_server/blob/main/README.md


environment:
  sdk: ^3.3.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mime: ^1.0.5
  path: ^1.9.0
  path_provider: ^2.1.2
  archive: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - lib/assets/index.html
